#pragma config(Sensor, in1,    Potmeter_sensor, sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorPotentiometer)
#pragma config(Sensor, in8,    Light_sensor,   sensorReflection)
#pragma config(Sensor, dgtl1,  Bump,           sensorTouch)
#pragma config(Sensor, dgtl2,  LimitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl3,  RotEncoder,     sensorRotation)
#pragma config(Sensor, dgtl4,  QuadEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  Sonar,          sensorSONAR_mm)
#pragma config(Sensor, dgtl12, Jumper,         sensorTouch)
#pragma config(Motor,  port1,           Motr,          tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           Servo,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*******************************************************************************
*
* This file is meant as a guide to working with sensors.
*
*******************************************************************************/
/*******************************************************************************
*
*  MOTORS & SENSORS:
*    [I/O Port]          [Name]              [Type]                [Description]                     *|
*  Motor  - Port 2      Servo          VEX 3-wire module      servo
*  Motor  - Port 3      Motr           VEX 3-wire module      motor
*  Analog - Port 1      Light_sensor
*  Analog - Port 2      Potmeter_sensor
*  Digital- Port 1      Bump
*  Digital- Port 2      LimitSwitch
*  Digital- Port 3      RotEncoder    VEX Shaft Encoder     Left side
*  Digital- Port 4,5    QuadEncoder   VEX Shaft Encoder     Right side
*  Digital- Port 6,7    Sonar         VEX Sonar Sensor      Front mounted, facing forward
*  Digital- Port 12     Jumper
*******************************************************************************/
// Functions Prototypes
void ServoMove(int servoPosition);
void MotorMove(int motorSpeed);
void WhichMotor(int waitTime, bool side);
// Declare Global Variables
bool doServo = true;
bool doMotor = false;
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main() {
// variables to be used:
  int   sonar_value;      // Will hold the current reading of the sonar sensor.
  int	light_value;
  int	potmeter_value;
  int   bumper_value;
  int   switch_value;
  int	encoder_value;
  int	timer_value;
  int minPos = 0;
  int min=1090;
  int minPot;
  potmeter_value = SensorValue(Potmeter_sensor);
  SensorValue[QuadEncoder] = 0;         //clear and reset the encoder
  SensorValue[RotEncoder] = 0;

while(true) {
// IF THE JUMPER IS NOT IN, DISPLAY THESE SENSORS:
	if(SensorValue(Jumper)) {
		ClearTimer(T1);
		light_value = SensorValue(Light_sensor);
		writeDebugStreamLine("light value = %d\n", light_value);
		potmeter_value = SensorValue(Potmeter_sensor);
		writeDebugStreamLine("potmeter value = %d\n", potmeter_value);
		bumper_value = SensorValue(Bump);
		writeDebugStreamLine("bumper value = %d\n", bumper_value);
		switch_value = SensorValue(LimitSwitch);
		writeDebugStreamLine("whisker value = %d\n", switch_value);
		wait1Msec(1000);
    //Gets the value of Timer T1 in 1ms increments and stores it in a variable
    timer_value = time1[T1];
		//printVal = (int)timerVal;
		writeDebugStreamLine("time to read these values = %d\n", timer_value);
		timer_value = time1[T3];
		writeDebugStream("time since start = %d\n", timer_value);
		writeDebugStreamLine("...................................");//(35) =limit of chars to put in debug stream....?
		if(doMotor){
		  for(int i = -127; i<127 ; i +=1) {
		  	MotorMove(i);
		  	}
		}
	}

	// ELSE DISPLAY FROM OTHER SENSORS:
	else {
		ClearTimer(T2);

	  writeDebugStreamLine("sonar value = %d\n", sonar_value);
		encoder_value = SensorValue(QuadEncoder);
		writeDebugStreamLine("Quad encoder value = %d\n", encoder_value);
		encoder_value = SensorValue(RotEncoder);
		writeDebugStreamLine("Rotation encoder value = %d\n", encoder_value);
    //Gets the value of Timer T2 in 1ms increments and stores it in a variable
    timer_value = time1[T2];
		writeDebugStreamLine("time to read these values = %d\n", timer_value);
		timer_value = time1[T3];
		writeDebugStreamLine("time since start = %d\n", timer_value);
		writeDebugStreamLine("...................................");//(35) =limit of chars to put in debug stream....?
		wait1Msec(10);




		if(doServo){
			motor[leftMotor] = 0;
  				motor[rightMotor] = 0;
		  for (int i = -127; i<127 ; i +=3)  {

		  	ServoMove(i);
		  	potmeter_value = SensorValue(Potmeter_sensor);
		  	light_value =SensorValue (Light_sensor);
		  	if (light_value < min){
		  		min = light_value;
		  		minPos = i;
		  		minPot = potmeter_value;
		  		}
					//if(i < 40 || i >100) {
					//	i+= 19;
		  		//}
		  		// Function to get potemeter values at specific angles.
		  		//if(i == -71 || i == 0 || i == 85){
		  		//	writeDebugStreamLine("Hey! %d", potmeter_value);
		  		//}
		  		//writeDebugStreamLine("%d",min);
		  		//if(i >= -28){
		  		//	minPot = SensorValue(Potmeter_sensor);
		  		//	break;
		  		//}
		  		}
		 // doServo = false;
      ServoMove(minPos);
    	writeDebugStreamLine("%d",minPos);
    	int angle = abs(180-(minPot - 3911.0944)/(-14.38668));
    	writeDebugStreamLine("Our final angle is: %d. final servo: %d, final potent %d",angle, minPos, minPot);
    	WhichMotor(abs(90-angle),(angle<90));
      min = 1090;
    }
	}
	}
}

void ServoMove(int servoPosition){
	int light_value =SensorValue (Light_sensor);
	int sonar_value = SensorValue(Sonar);
  writeDebugStreamLine("Servo Position = %d, Light Sensor = %d, Sonar = %d",servoPosition, light_value, sonar_value);
  motor[Servo] = servoPosition;
  wait1Msec(50);

}

void WhichMotor(int waitTime, bool side){
while(waitTime != 0){
	if (side){
		motor[rightMotor] = 60;
}
  else{
	  motor[leftMotor] =-60;
}
waitTime-=1;
wait1Msec(10);
}
int wait2 = 100;
int sonar_value = SensorValue(Sonar);
			else{
				while(wait2!=0){
	  		motor[leftMotor] = -60;
	  		motor[rightMotor] = 60;
	  		wait2-=1;
	  		wait1Msec(10);
	  	}
	  	}

}

void MotorMove(int motorSpeed){
  motor[Motr] = motorSpeed;
  writeDebugStream("Motor Speed = %d",motorSpeed);
  wait1Msec(1000);
}
