#pragma config(Sensor, in1,    Light,          sensorReflection)
#pragma config(Sensor, dgtl7,  Input,          sensorSONAR_mm)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*******************************************************************************
*
*  This file is meant as an introduction and as a template for developing
*  programs to run on the Vex controller.
*
*******************************************************************************/

/*******************************************************************************
*
*	main
*
*******************************************************************************/
task main()
{
//  int bumper = 1;	              // normal bumper state = 1; when pressed = 0

  wait1Msec(2000);    					// give stuff time to turn on

  int sensor_value;
	sensor_value = SensorValue(Input);

  while(true)
  {

  	//if (sensor_value < 70) {
  	//	sensor_value = 70;
  	//}
  	//if (sensor_value > 1090) {
  	//	sensor_value = 1090;
  	//}

  	//float percentage = 1.0 - (sensor_value-70.0)/1020.0;

  	//motor[leftMotor] = (int) (-127 * percentage);
  	//motor[rightMotor] = (int) (127 * percentage);
  	//if (sensor_value += 15.5)
  	//	{
  	//		motor[leftMotor] = -127; //fullspeed forward
	 	//		motor[rightMotor] = 127; //fullspeed forward
  	//	}
  	//else if (sensor_value >= 800)
  	//	{
  	//		motor[leftMotor] = -20;
  	//		motor[rightMotor] = 20;
  	//	}
  	//else
  	//	{
  	//		motor[leftMotor] = -60;
  	//		motor[rightMotor] = 60;
			//}
    //Joystick control of the motors
    motor[leftMotor]   =  vexRT[Ch3]; // up = CW

         // up = CCW
    motor[rightMotor]  = -vexRT[Ch2];

  //  //If the bumper is press, automatically backup
  //  while(!SensorValue[bump1])
  //  {
	 //   writeDebugStreamLine("bumped-backing up");

  //  	motor[leftMotor] = -127; //fullspeed backwards
	 //   motor[rightMotor] = 127; //fullspeed backwards
	 //   wait1Msec(1000);  // keep backing up for 1000ms (1 sec)

	 //   motor[leftMotor]  = 0;  //stop motors
	 //   motor[rightMotor] = 0;  //stop motors
	 //   wait1Msec(1000);
  //   }

  //   writeDebugStreamLine("bumper is clear");
  //}
 writeDebugStream("%d\n",sensor_value);
}
}
