#pragma config(Sensor, in1,    potSensor,      sensorPotentiometer)
#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  bump1,          sensorTouch)
#pragma config(Sensor, dgtl2,  bump2,          sensorTouch)
#pragma config(Sensor, dgtl3,  bump3,          sensorTouch)
#pragma config(Sensor, dgtl4,  bump4,          sensorTouch)
#pragma config(Sensor, dgtl11, Sonar,          sensorSONAR_mm)
#pragma config(Motor,  port2,           rightmotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftmotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           Servo,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// prototypes
void Right();
void Left();
void SLeft();
void SRight();
void Forward();
void Back();
void Stop();
void MasterPlan();
bool EventTrigger():
int newVal;

// main
task main() {
    while(true) {
      while(!EventTrigger){
       EventListener();
       motor[leftmotor]=127;
       motor[rightmotor]=-127;
      }
      Stop();
	    MasterPlan();
      EventListener = false;
    }
}

void EventListener(){
  if(SensorValue(bump1)!=0 || SensorValue(bump2)!=0  || SensorValue(bump3)!=0 || SensorValue(Sonar)>300 || SensorValue(Sonar) <250){
    EventTrigger = true;
  }

}

void MasterPlan(){
    newVal  = SensorValue(Sonar);

    //getting the dumbass out of corners
    if( SensorValue(bump4) != 0 && (SensorValue(bump1)!=0 || SensorValue(bump2)!=0  || SensorValue(bump3)!=0)){
      Stop();
      Back();
      Left();
      Back();
      Forward();
      Forward();
    }

    //if it bumps turn left
    else  if (SensorValue(bump1)!=0 || SensorValue(bump2)!=0  || SensorValue(bump3)!=0) {
        Stop();
        Back();
        Left();
        Forward();
    }

    //if there is no wall to the right turn right
    else if(newVal > 600){
        Stop();
        Forward();
        Right();
    }
    //if we are 300 mm from wall get closer to it
    else if(newVal >300){
        SRight();
    }
    //if we are less than 200 mm from wall get farther from it
    else if(newVal < 250){
        SLeft();
    }
}

void Stop() {
  motor[rightmotor]=0;
  motor[leftmotor]=0;
  wait10Msec(30);
}
void Left() {
  motor[leftmotor]=-70;
  motor[rightmotor]=-80;
  wait10Msec(40);
  Stop();
}
void SLeft() {
  motor[leftmotor]=-30;
  motor[rightmotor]=-30;
  wait10Msec(30);
  Stop();
}
void Right() {
  motor[rightmotor]=70;
  motor[leftmotor]=80;
  wait10Msec(35);
  Stop();
}
void SRight() {
  motor[leftmotor]=30;
  motor[rightmotor]=30;
  wait10Msec(30);
  Stop();
}
void Forward() {
  motor[leftmotor]=80;
  motor[rightmotor]=-120;
  wait10Msec(50);
  Stop();
}
void Back() {
  motor[leftmotor]=-90;
  motor[rightmotor]=120;
  wait10Msec(50);
  Stop();
}
